name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  integration-tests:
    name: ${{ matrix.host }}-${{ matrix.test }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {host: linux-x86_64, os: ubuntu-24.04, target_pattern: "//...", shell: bash}
          - {host: macos-arm64, os: macos-15, target_pattern: "//...", shell: bash}
          - {host: macos-x86_64, os: macos-15-intel, target_pattern: "//...", shell: bash}
          - {host: windows-x86_64, os: windows-2022, target_pattern: "//examples:local_bzlmod_test", shell: pwsh}
    env:
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      MSYS_NO_PATHCONV: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run integration tests
        run: >-
          bazel test ${{ matrix.target_pattern }}
          --bes_results_url=https://buildbuddy-toolchain.buildbuddy.io/invocation/
          --bes_backend=grpcs://buildbuddy-toolchain.buildbuddy.io
          --remote_cache=grpcs://buildbuddy-toolchain.buildbuddy.io
          --remote_timeout=2m
          --remote_header=x-buildbuddy-api-key="${{ env.BUILDBUDDY_API_KEY }}"
          --test_output=all
